### ISSUE TITLE
Offset option

### ISSUE THREAD

**Issue by lupinskij** [samccone/scrollin#11]
Create an option to simply pass an offset in order to have it fire later into the viewport.

**Comment by samccone** [comment]
I like this idea :+1:

**Comment by tomca32** [comment]
Or earlier! :)

This is pretty much what we need. We want to instantiate some stuff a bit before they enter the viewport so it's not so obvious for the user.

**Comment by samccone** [comment]
patch will be here
https://github.com/samccone/scrollin/blob/master/index.js#L10-L17

we will need a new offset options for 

```
top: {number},
left: {number}
```

And that his all I think :)

**Comment by tomca32** [comment]
Just figuring out what makes the most sense.

If you passed something like:

    track(el, whatever, {top: 100});

So with a 100px top offset, scrolling down, would you expect "whatever" to happen sooner or later than without offset?

**Comment by samccone** [comment]
Given these keys...
```
triggerTopOffset: <num>
triggerLeftOffset: <num>
```


Positive numbers will delay
Negative numbers will cause an earlier trigger


Thoughts?

**Comment by tomca32** [comment]
Cool, that's what I thought as well but wasn't sure if it made sense.

**Comment by samccone** [comment]
landed, thanks @tomca32 :clap:

**Comment by samccone** [comment]
v0.3.0 :sparkles:
