### ISSUE TITLE
Possible scroll handler leak

### ISSUE THREAD

**Issue by ianmstew** [samccone/scrollin#6]
This line removes the _onScroll method:
https://github.com/samccone/scrollin/blob/master/index.js#L41

This line adds a _throttled_ _onScroll method:
https://github.com/samccone/scrollin/blob/master/index.js#L49

Will the _onScroll handler never die since the function registered isn't the function deregistered?

**Comment by samccone** [comment]
Good spot fix incoming

**Comment by samccone** [comment]
Luckily it is only 1 scroll leak not N :)

**Comment by ianmstew** [comment]
Haha yeah more like a drop than a leak :)
